# Borrowed from here:  https://gist.github.com/dan-blanchard/7045057
# The validity of this file can be checked here: http://lint.travis-ci.org/

language: python
python:
    - "2.7"
    - "3.5"

# Setup anaconda
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=$HOME/miniconda2/bin:$PATH

# Install packages
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION -c conda-forge --file requirements.txt
  - conda install --yes pyflakes
  - python setup.py install
before_script:
  - python -m pyflakes .
script: 
  - "python setup.py test"