# Borrowed from here:  https://gist.github.com/dan-blanchard/7045057
# The validity of this file can be checked here: http://lint.travis-ci.org/

sudo: false
language: python
python:
    - "2.7"
    - "3.6"

before_install:
  # Setup miniconda
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=$HOME/miniconda3/bin:$PATH
  # Create a virtual environment with the right version of python
  - conda create -n testing python=$TRAVIS_PYTHON_VERSION --yes
  - source activate testing

# Install packages
install:
  - conda install --yes "numba<0.49" scipy h5py mkl
  - conda install --yes -c conda-forge mpi4py mpich
  - pip install pyflakes pytest==4.6
  - python setup.py install
before_script:
  - python -m pyflakes .
  - pip install openPMD-viewer
script:
  - "python setup.py test"

  # Run also the picmi test
  - pip install wget picmistandard numexpr periodictable
  - cd tests/unautomated ; curl https://raw.githubusercontent.com/picmi-standard/picmi/master/Examples/laser_acceleration/laser_acceleration_PICMI.py -o fbpic_script.py ; python test_picmi.py ; cd ../../

after_success:
  # Automatically upload the documentation when updating the master branch
  - ./deploy.sh
